// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuoxH33Yvh9rxVfpz6sve7exXwpYyi8ag',
    appId: '1:601446681635:web:9f54541054fed06d8f7596',
    messagingSenderId: '601446681635',
    projectId: 'todo-app-8eeb9',
    authDomain: 'todo-app-8eeb9.firebaseapp.com',
    storageBucket: 'todo-app-8eeb9.appspot.com',
    measurementId: 'G-96WR35YML3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrEpBY1kxRtcYniiLJmOELSaD0TpwM508',
    appId: '1:601446681635:android:d9632f6d878e0cfc8f7596',
    messagingSenderId: '601446681635',
    projectId: 'todo-app-8eeb9',
    storageBucket: 'todo-app-8eeb9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy8snc7d9Yvy_T4zexWdCd3TvH_VqUZDA',
    appId: '1:601446681635:ios:337985fb818dc56e8f7596',
    messagingSenderId: '601446681635',
    projectId: 'todo-app-8eeb9',
    storageBucket: 'todo-app-8eeb9.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );
}
